//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerModule.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CustomersDatabaseEntities : DbContext
    {
        public CustomersDatabaseEntities()
            : base("name=CustomersDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
    
        public virtual int Customers_Delete(ObjectParameter eRROR_NUMBER, ObjectParameter eRROR_MESSAGE, Nullable<int> customer_ID)
        {
            var customer_IDParameter = customer_ID.HasValue ?
                new ObjectParameter("Customer_ID", customer_ID) :
                new ObjectParameter("Customer_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Customers_Delete", eRROR_NUMBER, eRROR_MESSAGE, customer_IDParameter);
        }
    
        public virtual ObjectResult<Customers_Get_Result> Customers_Get(ObjectParameter eRROR_NUMBER, ObjectParameter eRROR_MESSAGE, Nullable<int> customer_ID)
        {
            var customer_IDParameter = customer_ID.HasValue ?
                new ObjectParameter("Customer_ID", customer_ID) :
                new ObjectParameter("Customer_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customers_Get_Result>("Customers_Get", eRROR_NUMBER, eRROR_MESSAGE, customer_IDParameter);
        }
    
        public virtual int Customers_Insert(ObjectParameter eRROR_NUMBER, ObjectParameter eRROR_MESSAGE, ObjectParameter customer_ID, string customer_Name, string customer_Surname, string customer_Phonenumber, string customer_Address)
        {
            var customer_NameParameter = customer_Name != null ?
                new ObjectParameter("Customer_Name", customer_Name) :
                new ObjectParameter("Customer_Name", typeof(string));
    
            var customer_SurnameParameter = customer_Surname != null ?
                new ObjectParameter("Customer_Surname", customer_Surname) :
                new ObjectParameter("Customer_Surname", typeof(string));
    
            var customer_PhonenumberParameter = customer_Phonenumber != null ?
                new ObjectParameter("Customer_Phonenumber", customer_Phonenumber) :
                new ObjectParameter("Customer_Phonenumber", typeof(string));
    
            var customer_AddressParameter = customer_Address != null ?
                new ObjectParameter("Customer_Address", customer_Address) :
                new ObjectParameter("Customer_Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Customers_Insert", eRROR_NUMBER, eRROR_MESSAGE, customer_ID, customer_NameParameter, customer_SurnameParameter, customer_PhonenumberParameter, customer_AddressParameter);
        }
    
        public virtual ObjectResult<Customers_Select_Result> Customers_Select(ObjectParameter eRROR_NUMBER, ObjectParameter eRROR_MESSAGE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customers_Select_Result>("Customers_Select", eRROR_NUMBER, eRROR_MESSAGE);
        }
    
        public virtual int Customers_Update(ObjectParameter eRROR_NUMBER, ObjectParameter eRROR_MESSAGE, Nullable<int> customer_ID, string customer_Name, string customer_Surname, string customer_Phonenumber, string customer_Address)
        {
            var customer_IDParameter = customer_ID.HasValue ?
                new ObjectParameter("Customer_ID", customer_ID) :
                new ObjectParameter("Customer_ID", typeof(int));
    
            var customer_NameParameter = customer_Name != null ?
                new ObjectParameter("Customer_Name", customer_Name) :
                new ObjectParameter("Customer_Name", typeof(string));
    
            var customer_SurnameParameter = customer_Surname != null ?
                new ObjectParameter("Customer_Surname", customer_Surname) :
                new ObjectParameter("Customer_Surname", typeof(string));
    
            var customer_PhonenumberParameter = customer_Phonenumber != null ?
                new ObjectParameter("Customer_Phonenumber", customer_Phonenumber) :
                new ObjectParameter("Customer_Phonenumber", typeof(string));
    
            var customer_AddressParameter = customer_Address != null ?
                new ObjectParameter("Customer_Address", customer_Address) :
                new ObjectParameter("Customer_Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Customers_Update", eRROR_NUMBER, eRROR_MESSAGE, customer_IDParameter, customer_NameParameter, customer_SurnameParameter, customer_PhonenumberParameter, customer_AddressParameter);
        }
    }
}
